In [2]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])
print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
#axis=0 means vertical addtion and axis =1 means horizontal addition 
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100*A/cal
#reshape can be used to make the matrix to wateva size u want
#here we are dividing a 3 by 4 matrix with a 1 by 4  matrix this is knwn as broadcasting
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
#tips to bug free
#do not use rank 1 arrays
A=np.random.rand(4)
print(A)
print(A.shape)
#it has a shape (4,), which is weird and it does not behave as a column or a row vector
# so instead use 


[0.41491782 0.95793196 0.46548744 0.64479319]
(4,)
[[0.69275597]
 [0.63467461]
 [0.82447196]
 [0.42008366]]
(4, 1)


In [13]:
B=np.random.rand(4,1)
print(B)
print(B.shape)
print(B.T)
# whereas A transpose wont give 

[[0.65637183]
 [0.85099061]
 [0.71172441]
 [0.54678922]]
(4, 1)
[[0.65637183 0.85099061 0.71172441 0.54678922]]
